service: iacserverlessaws
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iam:
      role:
          statements:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
                - dynamodb:Scan
              Resource:
                - arn:aws:dynamodb:us-east-1:xxxxxxxxxxxx:table/ProductCatalog

functions:

  insertItem:
    handler: files/insertItem.handler
    events:
      - http:
          path: /item
          method: post
  fetchItems:
    handler: files/fetchItems.handler
    events:
      - http:
          path: /items
          method: get
  fetchItem:
    handler: files/fetchItem.handler
    events:
      - http:
          path: /items/{id}
          method: get
  updateItem:
    handler: files/updateItem.handler
    events:
      - http:
          path: /items/{id}
          method: put

resources:
  Resources:
    ProductCatalog:
      Type: AWS::DynamoDB::Table
      Properties:
          TableName: ProductCatalog
          BillingMode: PAY_PER_REQUEST
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH